# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:04

from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('1', '헬스&뷰티'), ('2', '외국어'), ('3', '컴퓨터'), ('4', '음악 / 미술'), ('5', '스포츠'), ('6', '전공 / 취업'), ('7', '이색취미')], max_length=1)),
                ('class_type', models.CharField(choices=[('1', '1:1수업'), ('2', '그룹수업'), ('3', '원데이')], max_length=1)),
                ('min_member', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, null=True)),
                ('max_member', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, null=True)),
                ('cover_photo', models.ImageField(upload_to='class/cover/%Y/%m/%d')),
                ('tutor_intro', models.CharField(max_length=100)),
                ('class_intro', models.CharField(max_length=100)),
                ('target_intro', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('basic_class_time', models.CharField(max_length=1)),
                ('total_count', models.CharField(max_length=1)),
                ('youtube_url1', models.CharField(max_length=100, null=True)),
                ('youtube_url2', models.CharField(max_length=100, null=True)),
                ('region_comment', models.CharField(max_length=100, null=True)),
                ('notice', models.CharField(max_length=100, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiclass.Lecture'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
