# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.CharField(choices=[('hbn', '헬스&뷰티'), ('lang', '외국어'), ('com', '컴퓨터'), ('mna', '음악 / 미술'), ('sports', '스포츠'), ('major', '전공 / 취업'), ('hobby', '이색취미')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='class_type',
            field=models.CharField(choices=[('onetoone', '1:1수업'), ('group', '그룹수업'), ('oneday', '원데이')], max_length=1),
        ),
    ]
