# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='class_intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='target_intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='tutor_intro',
            field=models.TextField(),
        ),
    ]
