# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_photo', models.ImageField(upload_to='class/images/%Y/%m/%d')),
                ('curriculum_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='regiclass.Lecture')),
            ],
        ),
        migrations.AlterModelOptions(
            name='lecturephoto',
            options={},
        ),
        migrations.RenameField(
            model_name='lecturephoto',
            old_name='photo',
            new_name='lecture_photo',
        ),
        migrations.RemoveField(
            model_name='lecturephoto',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lecturephoto',
            name='photo_type',
        ),
    ]
