# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('info', ''), ('curriculum', '')], max_length=10)),
                ('photo', models.ImageField(upload_to='class/images/%Y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_photos', to='regiclass.Lecture')),
            ],
            options={
                'ordering': ['photo_type'],
            },
        ),
        migrations.AlterField(
            model_name='classlocation',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='regiclass.Lecture'),
        ),
    ]
