# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regiclass', '0002_auto_20170808_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_rate', models.CharField(default=0, max_length=1)),
                ('delivery_rate', models.CharField(default=0, max_length=1)),
                ('preparation_rate', models.CharField(default=0, max_length=1)),
                ('kindness_rate', models.CharField(default=0, max_length=1)),
                ('punctually_rate', models.CharField(default=0, max_length=1)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='state',
            field=models.CharField(choices=[('editing', '작성중'), ('activity', '활동중')], default='editing', max_length=8),
        ),
        migrations.AlterField(
            model_name='lecturephoto',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiclass.Lecture'),
        ),
        migrations.AddField(
            model_name='review',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiclass.Lecture'),
        ),
    ]
