# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0002_auto_20170808_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturephoto',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiclass.Lecture'),
        ),
    ]
