# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0002_auto_20170819_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='create_date',
        ),
    ]
