# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0003_remove_enrollment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_photo',
            field=models.ImageField(blank=True, null=True, upload_to='class/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='basic_class_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='notice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='region_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='total_count',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
