# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0003_auto_20170810_0031'),
    ]

    operations = [
    ]
