# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0006_auto_20170814_1302'),
        ('regiclass', '0004_auto_20170810_1334'),
    ]

    operations = [
    ]
