# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0007_merge_20170814_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='basic_class_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.CharField(choices=[('hbn', '헬스&뷰티'), ('lang', '외국어'), ('com', '컴퓨터'), ('mna', '음악 / 미술'), ('sports', '스포츠'), ('major', '전공 / 취업'), ('hobby', '이색취미')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='class_type',
            field=models.CharField(choices=[('onetoone', '1:1수업'), ('group', '그룹수업'), ('oneday', '원데이')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='state',
            field=models.CharField(choices=[('editing', '작성중'), ('activity', '활동중')], default='editing', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='total_count',
            field=models.CharField(max_length=10),
        ),
    ]
