# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0006_auto_20170815_1711'),
        ('regiclass', '0008_auto_20170814_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiclass.Lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.AddField(
            model_name='lecture',
            name='like_users',
            field=models.ManyToManyField(related_name='like_lecture', through='regiclass.LikeLecture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likelecture',
            unique_together=set([('user', 'lecture')]),
        ),
    ]
