# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0009_auto_20170815_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='curriculum_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='delivery_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='kindness_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='preparation_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='punctually_rate',
            field=models.IntegerField(default=0),
        ),
    ]
