# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('auth', '0008_alter_user_username_max_length'),
        ('regiclass', '0010_auto_20170816_1742'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiclass.Lecture')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='null', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_token',
            field=models.ManyToManyField(to='authtoken.Token'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cert_type',
            field=models.CharField(choices=[('univ', '대학인증'), ('grad', '대학원인증'), ('identity', '신분증인증')], max_length=8),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='status_type',
            field=models.CharField(choices=[('ing', '재학'), ('graduation', '졸업'), ('complete', '수료')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='enrollments',
            field=models.ManyToManyField(related_name='enroll_lectures', through='member.Enrollment', to='regiclass.Lecture'),
        ),
    ]
