# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import member.models.myuser


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('regiclass', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.myuser.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='class_location',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='class_talent',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='how_to_know',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='school_photo',
        ),
        migrations.AddField(
            model_name='myuser',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='myuser',
            name='enrollments',
            field=models.ManyToManyField(related_name='enroll_lectures', through='regiclass.Enrollment', to='regiclass.Lecture'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_token',
            field=models.ManyToManyField(to='authtoken.Token'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='identification',
            field=models.ImageField(null=True, upload_to='user/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='school',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_photo',
            field=models.ImageField(null=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
