# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170807_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cert_type',
            field=models.CharField(choices=[('대학', '대학인증'), ('대학원', '대학원인증'), ('신분증', '신분증인증')], max_length=1),
        ),
    ]
