# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170820_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='member.Tutor'),
        ),
    ]
