# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170818_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='slug',
        ),
    ]
