# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import member.models.myuser


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('member', '0002_auto_20170801_1333'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.myuser.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_token',
            field=models.ManyToManyField(to='authtoken.Token'),
        ),
    ]
