# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_myuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
