# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_myuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
