# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiclass', '0008_auto_20170814_1635'),
        ('member', '0005_auto_20170814_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiclass.Lecture')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='enrollments',
            field=models.ManyToManyField(related_name='enroll_lectures', through='member.Enrollment', to='regiclass.Lecture'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
