# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_myuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=24),
        ),
    ]
