# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170820_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='slug',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
